server:
  servlet:
    context-path: /
  port: 2022

spring:
  banner:
    location: banner.txt
  profiles:
    active: dev
  jackson: 
    serialization: 
      fail-on-empty-beans: false
      indent-output: true